apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-java
          image: shikhorroy/simple-spring-boot-app:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
